apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-prometheus
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/Smitty-0881/helm-charts.git
    targetRevision: main
    chart: obs-prometheus
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://192.168.4.96:16443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
